### ISSUE TITLE
Using transifex

### ISSUE THREAD

**Issue by mokhin-denis** [Mikolaytis/LaitisTranslation#1]
Пробовали [transifex](https://www.transifex.com/) для управления переводом?

**Comment by mklts** [comment]
Здравствуйте, не пробовал. Проблема перевода и его версионности для меня чужда. Просто не сталкивался, этим занимались другие команды специалистов. 

Любая интеграция с подобными вещами требует серьезного вклада для входа. 
На данный момент есть вещи поважнее (улучшение программы и т.п.).
В будущем, вернусь к этому вопросу, когда будет цель качественно перевести на 5+ языков.
